[package]
name = "profile-shared"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
ed25519-dalek = { workspace = true }
zeroize = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
sha2 = "0.10"
